server.port=8001

server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=AnalyzerMcpServer

# ====SpringAIAlibaba Config=============
spring.ai.dashscope.api-key=${aliQwen-api}
spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com
spring.ai.dashscope.chat.options.model=qwen3-max-2026-01-23

# mcp server config
#spring.ai.mcp.server.type=async
spring.ai.mcp.server.name=shell-exe-mcp-server
spring.ai.mcp.server.version=1.0.0

#spring.ai.dashscope.chat.options.model=qwen-flash-character
#spring.ai.dashscope.chat.options.model=qwen-flash-character-2026-02-26
# ====SpringAI Config=============
#spring.ai.openai.api-key=${aliQwen-api}
#spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode
#spring.ai.openai.chat.options.model=qwen-plus